

#---
server:
  port: 8080
  servlet:
    context-path: /
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 9052

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      #naming: physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
    generate-ddl: true

  redis:
    host: 127.0.0.1
    port: 6379
---
server:
  port: 8080
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rds-prod.cbhccc1fu4rv.ap-northeast-2.rds.amazonaws.com:3306/prod?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin9052!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      #naming: physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true

  redis:
    host: 127.0.0.1
    port: 6379
#---